version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brain_agriculture
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: brain_agriculture

  adminer:
    image: adminer # Use the latest Adminer image
    container_name: adminer-brain-agriculture
    restart: always
    ports:
      - '8080:8080' # Expose Adminer on port 8080
    environment:
      ADMINER_DESIGN: pepa_lind

volumes:
  pgdata:
