# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Brain Agriculture CI - Dev

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn ci:lint

      - name: Type checking
        run: yarn typecheck

      - name: Run Unit Tests
        run: yarn test

      - name: Run E2E Tests (shared DB)
        env:
          NODE_ENV: development
          DB_HOST: ${{ secrets.DB_HOST_RAILWAY_DEVELOP }}
          DB_USERNAME: ${{ secrets.DB_USERNAME_RAILWAY_DEVELOP }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_RAILWAY_DEVELOP }}
          DB_NAME: ${{ secrets.DB_NAME_RAILWAY_DEVELOP }}
          DB_PORT: ${{ secrets.DB_PORT_RAILWAY_DEVELOP }}
        run: |
          echo "⚠️ Rodando E2E usando banco real"
          yarn test:e2e
